package permissions

import access "github.com/zarkones/ControlACCESS"

const (
	AGENTS_LIST = access.PermissionKey(iota) + 1

	MESSAGES_LIST
	MESSAGES_INSERT

	PROFILES_LIST
	PROFILES_INSERT
	PROFILES_UPDATE
	PROFILES_DELETE

	LISTENERS_LIST

	PERMISSIONS_LIST
	PERMISSIONS_INSERT
	PERMISSIONS_DELETE

	OPERATORS_LIST
)

var AllPermissions = []access.PermissionKey{
	AGENTS_LIST,
	MESSAGES_LIST,
	MESSAGES_INSERT,
	PROFILES_LIST,
	PROFILES_INSERT,
	PROFILES_UPDATE,
	PROFILES_DELETE,
	LISTENERS_LIST,
	PERMISSIONS_LIST,
	PERMISSIONS_INSERT,
	PERMISSIONS_DELETE,
	OPERATORS_LIST,
}
